[tool.poetry]
name = "casm-xengine"
version = "0.1.0"
description = ""
authors = ["liamconnor <liam.dean.connor@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
blimpy = "^2.1.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
